# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e1ad23a1679f9b04bb4b0965dc62f0a27b9a50ccc2b8237165262959ff69ced0ca56be7e780f76735b7057609bdbe6f33687b56bba833da2fb34576a3a225b

test:
  secret_key_base: 76fdc8cd7afbd2d961754b48c0e06045a85b505bc5166f485a2ae02a58990f7651c7b8b8444ca42db2a2608f7a5d36c1bb09e7971febc35c82f7eb12e6a80b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
