source "https://rubygems.org"
ruby "2.3.1"

gem "active_model_serializers"
gem "kaminari"
gem "numbers_and_words"
gem "pg", "~> 0.18"
gem "puma", "~> 3.0"
gem "rack-cors", require: "rack/cors"
gem "rails", "~> 5.0.0", ">= 5.0.0.1"

group :development, :test do
  gem "capybara"
  gem "database_rewinder"
  gem "factory_girl_rails"
  gem "faker"
  gem "pry"
  gem "pry-byebug"
  gem "rspec-rails"
end

group :development do
  gem "guard-rspec", require: false
  gem "listen", "~> 3.0.5"
  gem "rubocop", require: false
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :production do
  gem 'rails_12factor'
  gem 'rails_serve_static_assets'
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
